/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AlternativeAppliance;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AlternativeApplianceList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class AlternativeApplianceList {
  @SerializedName("AlternativeAppliance")
  private AlternativeAppliance alternativeAppliance = null;

  public AlternativeApplianceList alternativeAppliance(AlternativeAppliance alternativeAppliance) {
    this.alternativeAppliance = alternativeAppliance;
    return this;
  }

   /**
   * Get alternativeAppliance
   * @return alternativeAppliance
  **/
  @Schema(description = "")
  public AlternativeAppliance getAlternativeAppliance() {
    return alternativeAppliance;
  }

  public void setAlternativeAppliance(AlternativeAppliance alternativeAppliance) {
    this.alternativeAppliance = alternativeAppliance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlternativeApplianceList alternativeApplianceList = (AlternativeApplianceList) o;
    return Objects.equals(this.alternativeAppliance, alternativeApplianceList.alternativeAppliance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternativeAppliance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlternativeApplianceList {\n");
    
    sb.append("    alternativeAppliance: ").append(toIndentedString(alternativeAppliance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
