/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BabyPlan;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BabyPlanList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class BabyPlanList {
  @SerializedName("BabyPlan")
  private BabyPlan babyPlan = null;

  public BabyPlanList babyPlan(BabyPlan babyPlan) {
    this.babyPlan = babyPlan;
    return this;
  }

   /**
   * Get babyPlan
   * @return babyPlan
  **/
  @Schema(description = "")
  public BabyPlan getBabyPlan() {
    return babyPlan;
  }

  public void setBabyPlan(BabyPlan babyPlan) {
    this.babyPlan = babyPlan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BabyPlanList babyPlanList = (BabyPlanList) o;
    return Objects.equals(this.babyPlan, babyPlanList.babyPlan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(babyPlan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BabyPlanList {\n");
    
    sb.append("    babyPlan: ").append(toIndentedString(babyPlan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
