/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Item;
import io.swagger.client.model.ItemGetPriceDetails;
import io.swagger.client.model.ItemID;
import io.swagger.client.model.ItemURN;
import io.swagger.client.model.MailerDetails;
import io.swagger.client.model.SourceEvent;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateItemReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class CreateItemReq {
  @SerializedName("SourceEvent")
  private SourceEvent sourceEvent = null;

  @SerializedName("IsItemOwned")
  private String isItemOwned = null;

  @SerializedName("ItemID")
  private ItemID itemID = null;

  @SerializedName("ItemURN")
  private ItemURN itemURN = null;

  @SerializedName("Item")
  private Item item = null;

  @SerializedName("RegisterMailer")
  private String registerMailer = null;

  @SerializedName("ItemGetPriceDetails")
  private ItemGetPriceDetails itemGetPriceDetails = null;

  @SerializedName("CustomerToken")
  private String customerToken = null;

  @SerializedName("PersonEID")
  private String personEID = null;

  @SerializedName("MailerDetails")
  private MailerDetails mailerDetails = null;

  public CreateItemReq sourceEvent(SourceEvent sourceEvent) {
    this.sourceEvent = sourceEvent;
    return this;
  }

   /**
   * Get sourceEvent
   * @return sourceEvent
  **/
  @Schema(description = "")
  public SourceEvent getSourceEvent() {
    return sourceEvent;
  }

  public void setSourceEvent(SourceEvent sourceEvent) {
    this.sourceEvent = sourceEvent;
  }

  public CreateItemReq isItemOwned(String isItemOwned) {
    this.isItemOwned = isItemOwned;
    return this;
  }

   /**
   * Get isItemOwned
   * @return isItemOwned
  **/
  @Schema(description = "")
  public String getIsItemOwned() {
    return isItemOwned;
  }

  public void setIsItemOwned(String isItemOwned) {
    this.isItemOwned = isItemOwned;
  }

  public CreateItemReq itemID(ItemID itemID) {
    this.itemID = itemID;
    return this;
  }

   /**
   * Get itemID
   * @return itemID
  **/
  @Schema(description = "")
  public ItemID getItemID() {
    return itemID;
  }

  public void setItemID(ItemID itemID) {
    this.itemID = itemID;
  }

  public CreateItemReq itemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
    return this;
  }

   /**
   * Get itemURN
   * @return itemURN
  **/
  @Schema(description = "")
  public ItemURN getItemURN() {
    return itemURN;
  }

  public void setItemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
  }

  public CreateItemReq item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @Schema(description = "")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }

  public CreateItemReq registerMailer(String registerMailer) {
    this.registerMailer = registerMailer;
    return this;
  }

   /**
   * Get registerMailer
   * @return registerMailer
  **/
  @Schema(description = "")
  public String getRegisterMailer() {
    return registerMailer;
  }

  public void setRegisterMailer(String registerMailer) {
    this.registerMailer = registerMailer;
  }

  public CreateItemReq itemGetPriceDetails(ItemGetPriceDetails itemGetPriceDetails) {
    this.itemGetPriceDetails = itemGetPriceDetails;
    return this;
  }

   /**
   * Get itemGetPriceDetails
   * @return itemGetPriceDetails
  **/
  @Schema(description = "")
  public ItemGetPriceDetails getItemGetPriceDetails() {
    return itemGetPriceDetails;
  }

  public void setItemGetPriceDetails(ItemGetPriceDetails itemGetPriceDetails) {
    this.itemGetPriceDetails = itemGetPriceDetails;
  }

  public CreateItemReq customerToken(String customerToken) {
    this.customerToken = customerToken;
    return this;
  }

   /**
   * Get customerToken
   * @return customerToken
  **/
  @Schema(description = "")
  public String getCustomerToken() {
    return customerToken;
  }

  public void setCustomerToken(String customerToken) {
    this.customerToken = customerToken;
  }

  public CreateItemReq personEID(String personEID) {
    this.personEID = personEID;
    return this;
  }

   /**
   * Get personEID
   * @return personEID
  **/
  @Schema(description = "")
  public String getPersonEID() {
    return personEID;
  }

  public void setPersonEID(String personEID) {
    this.personEID = personEID;
  }

  public CreateItemReq mailerDetails(MailerDetails mailerDetails) {
    this.mailerDetails = mailerDetails;
    return this;
  }

   /**
   * Get mailerDetails
   * @return mailerDetails
  **/
  @Schema(description = "")
  public MailerDetails getMailerDetails() {
    return mailerDetails;
  }

  public void setMailerDetails(MailerDetails mailerDetails) {
    this.mailerDetails = mailerDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateItemReq createItemReq = (CreateItemReq) o;
    return Objects.equals(this.sourceEvent, createItemReq.sourceEvent) &&
        Objects.equals(this.isItemOwned, createItemReq.isItemOwned) &&
        Objects.equals(this.itemID, createItemReq.itemID) &&
        Objects.equals(this.itemURN, createItemReq.itemURN) &&
        Objects.equals(this.item, createItemReq.item) &&
        Objects.equals(this.registerMailer, createItemReq.registerMailer) &&
        Objects.equals(this.itemGetPriceDetails, createItemReq.itemGetPriceDetails) &&
        Objects.equals(this.customerToken, createItemReq.customerToken) &&
        Objects.equals(this.personEID, createItemReq.personEID) &&
        Objects.equals(this.mailerDetails, createItemReq.mailerDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceEvent, isItemOwned, itemID, itemURN, item, registerMailer, itemGetPriceDetails, customerToken, personEID, mailerDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateItemReq {\n");
    
    sb.append("    sourceEvent: ").append(toIndentedString(sourceEvent)).append("\n");
    sb.append("    isItemOwned: ").append(toIndentedString(isItemOwned)).append("\n");
    sb.append("    itemID: ").append(toIndentedString(itemID)).append("\n");
    sb.append("    itemURN: ").append(toIndentedString(itemURN)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    registerMailer: ").append(toIndentedString(registerMailer)).append("\n");
    sb.append("    itemGetPriceDetails: ").append(toIndentedString(itemGetPriceDetails)).append("\n");
    sb.append("    customerToken: ").append(toIndentedString(customerToken)).append("\n");
    sb.append("    personEID: ").append(toIndentedString(personEID)).append("\n");
    sb.append("    mailerDetails: ").append(toIndentedString(mailerDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
