/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ErrorResponseList;
import io.swagger.client.model.ItemDetailsList;
import io.swagger.client.model.Source;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * GetItemDetailsResp
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class GetItemDetailsResp {
  @SerializedName("Source")
  private Source source = null;

  @SerializedName("ItemDetailsList")
  private ItemDetailsList itemDetailsList = null;

  @SerializedName("ErrorResponseList")
  private ErrorResponseList errorResponseList = null;

  public GetItemDetailsResp source(Source source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(description = "")
  public Source getSource() {
    return source;
  }

  public void setSource(Source source) {
    this.source = source;
  }

  public GetItemDetailsResp itemDetailsList(ItemDetailsList itemDetailsList) {
    this.itemDetailsList = itemDetailsList;
    return this;
  }

   /**
   * Get itemDetailsList
   * @return itemDetailsList
  **/
  @Schema(description = "")
  public ItemDetailsList getItemDetailsList() {
    return itemDetailsList;
  }

  public void setItemDetailsList(ItemDetailsList itemDetailsList) {
    this.itemDetailsList = itemDetailsList;
  }

  public GetItemDetailsResp errorResponseList(ErrorResponseList errorResponseList) {
    this.errorResponseList = errorResponseList;
    return this;
  }

   /**
   * Get errorResponseList
   * @return errorResponseList
  **/
  @Schema(description = "")
  public ErrorResponseList getErrorResponseList() {
    return errorResponseList;
  }

  public void setErrorResponseList(ErrorResponseList errorResponseList) {
    this.errorResponseList = errorResponseList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetItemDetailsResp getItemDetailsResp = (GetItemDetailsResp) o;
    return Objects.equals(this.source, getItemDetailsResp.source) &&
        Objects.equals(this.itemDetailsList, getItemDetailsResp.itemDetailsList) &&
        Objects.equals(this.errorResponseList, getItemDetailsResp.errorResponseList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(source, itemDetailsList, errorResponseList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetItemDetailsResp {\n");
    
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    itemDetailsList: ").append(toIndentedString(itemDetailsList)).append("\n");
    sb.append("    errorResponseList: ").append(toIndentedString(errorResponseList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
