/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ItemLink
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class ItemLink {
  @SerializedName("MemIdNum")
  private String memIdNum = null;

  @SerializedName("SrcCode")
  private String srcCode = null;

  public ItemLink memIdNum(String memIdNum) {
    this.memIdNum = memIdNum;
    return this;
  }

   /**
   * Get memIdNum
   * @return memIdNum
  **/
  @Schema(description = "")
  public String getMemIdNum() {
    return memIdNum;
  }

  public void setMemIdNum(String memIdNum) {
    this.memIdNum = memIdNum;
  }

  public ItemLink srcCode(String srcCode) {
    this.srcCode = srcCode;
    return this;
  }

   /**
   * Get srcCode
   * @return srcCode
  **/
  @Schema(description = "")
  public String getSrcCode() {
    return srcCode;
  }

  public void setSrcCode(String srcCode) {
    this.srcCode = srcCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemLink itemLink = (ItemLink) o;
    return Objects.equals(this.memIdNum, itemLink.memIdNum) &&
        Objects.equals(this.srcCode, itemLink.srcCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memIdNum, srcCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemLink {\n");
    
    sb.append("    memIdNum: ").append(toIndentedString(memIdNum)).append("\n");
    sb.append("    srcCode: ").append(toIndentedString(srcCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
