/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ItemURN
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class ItemURN {
  @SerializedName("ClientURN")
  private String clientURN = null;

  @SerializedName("ApplianceToken")
  private String applianceToken = null;

  public ItemURN clientURN(String clientURN) {
    this.clientURN = clientURN;
    return this;
  }

   /**
   * Get clientURN
   * @return clientURN
  **/
  @Schema(description = "")
  public String getClientURN() {
    return clientURN;
  }

  public void setClientURN(String clientURN) {
    this.clientURN = clientURN;
  }

  public ItemURN applianceToken(String applianceToken) {
    this.applianceToken = applianceToken;
    return this;
  }

   /**
   * Get applianceToken
   * @return applianceToken
  **/
  @Schema(description = "")
  public String getApplianceToken() {
    return applianceToken;
  }

  public void setApplianceToken(String applianceToken) {
    this.applianceToken = applianceToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemURN itemURN = (ItemURN) o;
    return Objects.equals(this.clientURN, itemURN.clientURN) &&
        Objects.equals(this.applianceToken, itemURN.applianceToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientURN, applianceToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemURN {\n");
    
    sb.append("    clientURN: ").append(toIndentedString(clientURN)).append("\n");
    sb.append("    applianceToken: ").append(toIndentedString(applianceToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
