/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.GetPriceCallSourceList;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ItemGetPriceDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class ItemGetPriceDetails {
  @SerializedName("ItemCreateOffer")
  private String itemCreateOffer = null;

  @SerializedName("GetPriceCallSourceList")
  private GetPriceCallSourceList getPriceCallSourceList = null;

  public ItemGetPriceDetails itemCreateOffer(String itemCreateOffer) {
    this.itemCreateOffer = itemCreateOffer;
    return this;
  }

   /**
   * Get itemCreateOffer
   * @return itemCreateOffer
  **/
  @Schema(description = "")
  public String getItemCreateOffer() {
    return itemCreateOffer;
  }

  public void setItemCreateOffer(String itemCreateOffer) {
    this.itemCreateOffer = itemCreateOffer;
  }

  public ItemGetPriceDetails getPriceCallSourceList(GetPriceCallSourceList getPriceCallSourceList) {
    this.getPriceCallSourceList = getPriceCallSourceList;
    return this;
  }

   /**
   * Get getPriceCallSourceList
   * @return getPriceCallSourceList
  **/
  @Schema(description = "")
  public GetPriceCallSourceList getGetPriceCallSourceList() {
    return getPriceCallSourceList;
  }

  public void setGetPriceCallSourceList(GetPriceCallSourceList getPriceCallSourceList) {
    this.getPriceCallSourceList = getPriceCallSourceList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemGetPriceDetails itemGetPriceDetails = (ItemGetPriceDetails) o;
    return Objects.equals(this.itemCreateOffer, itemGetPriceDetails.itemCreateOffer) &&
        Objects.equals(this.getPriceCallSourceList, itemGetPriceDetails.getPriceCallSourceList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemCreateOffer, getPriceCallSourceList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemGetPriceDetails {\n");
    
    sb.append("    itemCreateOffer: ").append(toIndentedString(itemCreateOffer)).append("\n");
    sb.append("    getPriceCallSourceList: ").append(toIndentedString(getPriceCallSourceList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
