/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.NewBabyPlan;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NewBabyPlanList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class NewBabyPlanList {
  @SerializedName("NewBabyPlan")
  private NewBabyPlan newBabyPlan = null;

  public NewBabyPlanList newBabyPlan(NewBabyPlan newBabyPlan) {
    this.newBabyPlan = newBabyPlan;
    return this;
  }

   /**
   * Get newBabyPlan
   * @return newBabyPlan
  **/
  @Schema(description = "")
  public NewBabyPlan getNewBabyPlan() {
    return newBabyPlan;
  }

  public void setNewBabyPlan(NewBabyPlan newBabyPlan) {
    this.newBabyPlan = newBabyPlan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewBabyPlanList newBabyPlanList = (NewBabyPlanList) o;
    return Objects.equals(this.newBabyPlan, newBabyPlanList.newBabyPlan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newBabyPlan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewBabyPlanList {\n");
    
    sb.append("    newBabyPlan: ").append(toIndentedString(newBabyPlan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
