/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Item;
import io.swagger.client.model.ItemID;
import io.swagger.client.model.ItemURN;
import io.swagger.client.model.Mailer;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * NewBabyPlan
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class NewBabyPlan {
  @SerializedName("ItemID")
  private ItemID itemID = null;

  @SerializedName("ItemURN")
  private ItemURN itemURN = null;

  @SerializedName("Mailer")
  private Mailer mailer = null;

  @SerializedName("Item")
  private Item item = null;

  public NewBabyPlan itemID(ItemID itemID) {
    this.itemID = itemID;
    return this;
  }

   /**
   * Get itemID
   * @return itemID
  **/
  @Schema(description = "")
  public ItemID getItemID() {
    return itemID;
  }

  public void setItemID(ItemID itemID) {
    this.itemID = itemID;
  }

  public NewBabyPlan itemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
    return this;
  }

   /**
   * Get itemURN
   * @return itemURN
  **/
  @Schema(description = "")
  public ItemURN getItemURN() {
    return itemURN;
  }

  public void setItemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
  }

  public NewBabyPlan mailer(Mailer mailer) {
    this.mailer = mailer;
    return this;
  }

   /**
   * Get mailer
   * @return mailer
  **/
  @Schema(description = "")
  public Mailer getMailer() {
    return mailer;
  }

  public void setMailer(Mailer mailer) {
    this.mailer = mailer;
  }

  public NewBabyPlan item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @Schema(description = "")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewBabyPlan newBabyPlan = (NewBabyPlan) o;
    return Objects.equals(this.itemID, newBabyPlan.itemID) &&
        Objects.equals(this.itemURN, newBabyPlan.itemURN) &&
        Objects.equals(this.mailer, newBabyPlan.mailer) &&
        Objects.equals(this.item, newBabyPlan.item);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemID, itemURN, mailer, item);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewBabyPlan {\n");
    
    sb.append("    itemID: ").append(toIndentedString(itemID)).append("\n");
    sb.append("    itemURN: ").append(toIndentedString(itemURN)).append("\n");
    sb.append("    mailer: ").append(toIndentedString(mailer)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
