/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.PersonUser;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PersonUserList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class PersonUserList {
  @SerializedName("PersonUser")
  private PersonUser personUser = null;

  public PersonUserList personUser(PersonUser personUser) {
    this.personUser = personUser;
    return this;
  }

   /**
   * Get personUser
   * @return personUser
  **/
  @Schema(description = "")
  public PersonUser getPersonUser() {
    return personUser;
  }

  public void setPersonUser(PersonUser personUser) {
    this.personUser = personUser;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonUserList personUserList = (PersonUserList) o;
    return Objects.equals(this.personUser, personUserList.personUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personUser);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonUserList {\n");
    
    sb.append("    personUser: ").append(toIndentedString(personUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
