/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PersonOwner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class PersonOwner {
  @SerializedName("PreviousClientURN")
  private String previousClientURN = null;

  @SerializedName("ClientURN")
  private String clientURN = null;

  @SerializedName("PreviousEID")
  private String previousEID = null;

  @SerializedName("EID")
  private String EID = "rt";

  @SerializedName("SrcCode")
  private String srcCode = null;

  public PersonOwner previousClientURN(String previousClientURN) {
    this.previousClientURN = previousClientURN;
    return this;
  }

   /**
   * Get previousClientURN
   * @return previousClientURN
  **/
  @Schema(description = "")
  public String getPreviousClientURN() {
    return previousClientURN;
  }

  public void setPreviousClientURN(String previousClientURN) {
    this.previousClientURN = previousClientURN;
  }

  public PersonOwner clientURN(String clientURN) {
    this.clientURN = clientURN;
    return this;
  }

   /**
   * Get clientURN
   * @return clientURN
  **/
  @Schema(description = "")
  public String getClientURN() {
    return clientURN;
  }

  public void setClientURN(String clientURN) {
    this.clientURN = clientURN;
  }

  public PersonOwner previousEID(String previousEID) {
    this.previousEID = previousEID;
    return this;
  }

   /**
   * Get previousEID
   * @return previousEID
  **/
  @Schema(description = "")
  public String getPreviousEID() {
    return previousEID;
  }

  public void setPreviousEID(String previousEID) {
    this.previousEID = previousEID;
  }

  public PersonOwner EID(String EID) {
    this.EID = EID;
    return this;
  }

   /**
   * employee ID
   * @return EID
  **/
  @Schema(example = "sdf", description = "employee ID")
  public String getEID() {
    return EID;
  }

  public void setEID(String EID) {
    this.EID = EID;
  }

  public PersonOwner srcCode(String srcCode) {
    this.srcCode = srcCode;
    return this;
  }

   /**
   * Get srcCode
   * @return srcCode
  **/
  @Schema(description = "")
  public String getSrcCode() {
    return srcCode;
  }

  public void setSrcCode(String srcCode) {
    this.srcCode = srcCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonOwner personOwner = (PersonOwner) o;
    return Objects.equals(this.previousClientURN, personOwner.previousClientURN) &&
        Objects.equals(this.clientURN, personOwner.clientURN) &&
        Objects.equals(this.previousEID, personOwner.previousEID) &&
        Objects.equals(this.EID, personOwner.EID) &&
        Objects.equals(this.srcCode, personOwner.srcCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(previousClientURN, clientURN, previousEID, EID, srcCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonOwner {\n");
    
    sb.append("    previousClientURN: ").append(toIndentedString(previousClientURN)).append("\n");
    sb.append("    clientURN: ").append(toIndentedString(clientURN)).append("\n");
    sb.append("    previousEID: ").append(toIndentedString(previousEID)).append("\n");
    sb.append("    EID: ").append(toIndentedString(EID)).append("\n");
    sb.append("    srcCode: ").append(toIndentedString(srcCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
