/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.RTPOfferReference;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RTPOfferReferenceList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class RTPOfferReferenceList {
  @SerializedName("RTPOfferReference")
  private RTPOfferReference rtPOfferReference = null;

  public RTPOfferReferenceList rtPOfferReference(RTPOfferReference rtPOfferReference) {
    this.rtPOfferReference = rtPOfferReference;
    return this;
  }

   /**
   * Get rtPOfferReference
   * @return rtPOfferReference
  **/
  @Schema(description = "")
  public RTPOfferReference getRtPOfferReference() {
    return rtPOfferReference;
  }

  public void setRtPOfferReference(RTPOfferReference rtPOfferReference) {
    this.rtPOfferReference = rtPOfferReference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RTPOfferReferenceList rtPOfferReferenceList = (RTPOfferReferenceList) o;
    return Objects.equals(this.rtPOfferReference, rtPOfferReferenceList.rtPOfferReference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rtPOfferReference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RTPOfferReferenceList {\n");
    
    sb.append("    rtPOfferReference: ").append(toIndentedString(rtPOfferReference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
