/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CallSourceDetails;
import io.swagger.client.model.RTPOfferDetails;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RTPRate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class RTPRate {
  @SerializedName("CallSourceDetails")
  private CallSourceDetails callSourceDetails = null;

  @SerializedName("RTPOfferDetails")
  private RTPOfferDetails rtPOfferDetails = null;

  public RTPRate callSourceDetails(CallSourceDetails callSourceDetails) {
    this.callSourceDetails = callSourceDetails;
    return this;
  }

   /**
   * Get callSourceDetails
   * @return callSourceDetails
  **/
  @Schema(description = "")
  public CallSourceDetails getCallSourceDetails() {
    return callSourceDetails;
  }

  public void setCallSourceDetails(CallSourceDetails callSourceDetails) {
    this.callSourceDetails = callSourceDetails;
  }

  public RTPRate rtPOfferDetails(RTPOfferDetails rtPOfferDetails) {
    this.rtPOfferDetails = rtPOfferDetails;
    return this;
  }

   /**
   * Get rtPOfferDetails
   * @return rtPOfferDetails
  **/
  @Schema(description = "")
  public RTPOfferDetails getRtPOfferDetails() {
    return rtPOfferDetails;
  }

  public void setRtPOfferDetails(RTPOfferDetails rtPOfferDetails) {
    this.rtPOfferDetails = rtPOfferDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RTPRate rtPRate = (RTPRate) o;
    return Objects.equals(this.callSourceDetails, rtPRate.callSourceDetails) &&
        Objects.equals(this.rtPOfferDetails, rtPRate.rtPOfferDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callSourceDetails, rtPOfferDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RTPRate {\n");
    
    sb.append("    callSourceDetails: ").append(toIndentedString(callSourceDetails)).append("\n");
    sb.append("    rtPOfferDetails: ").append(toIndentedString(rtPOfferDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
