/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Item;
import io.swagger.client.model.ItemID;
import io.swagger.client.model.ItemURN;
import io.swagger.client.model.Mailer;
import io.swagger.client.model.NewBabyPlanList;
import io.swagger.client.model.Plan;
import io.swagger.client.model.SourceEvent;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateItemReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class UpdateItemReq {
  @SerializedName("SourceEvent")
  private SourceEvent sourceEvent = null;

  @SerializedName("ItemID")
  private ItemID itemID = null;

  @SerializedName("ItemURN")
  private ItemURN itemURN = null;

  @SerializedName("Item")
  private Item item = null;

  @SerializedName("Plan")
  private Plan plan = null;

  @SerializedName("IsNewBabyPlan")
  private String isNewBabyPlan = null;

  @SerializedName("NewBabyPlanList")
  private NewBabyPlanList newBabyPlanList = null;

  @SerializedName("Mailer")
  private Mailer mailer = null;

  @SerializedName("UpdateMailerStatus")
  private String updateMailerStatus = null;

  @SerializedName("CustomerToken")
  private String customerToken = null;

  @SerializedName("OvrBabyBSD")
  private String ovrBabyBSD = null;

  public UpdateItemReq sourceEvent(SourceEvent sourceEvent) {
    this.sourceEvent = sourceEvent;
    return this;
  }

   /**
   * Get sourceEvent
   * @return sourceEvent
  **/
  @Schema(description = "")
  public SourceEvent getSourceEvent() {
    return sourceEvent;
  }

  public void setSourceEvent(SourceEvent sourceEvent) {
    this.sourceEvent = sourceEvent;
  }

  public UpdateItemReq itemID(ItemID itemID) {
    this.itemID = itemID;
    return this;
  }

   /**
   * Get itemID
   * @return itemID
  **/
  @Schema(description = "")
  public ItemID getItemID() {
    return itemID;
  }

  public void setItemID(ItemID itemID) {
    this.itemID = itemID;
  }

  public UpdateItemReq itemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
    return this;
  }

   /**
   * Get itemURN
   * @return itemURN
  **/
  @Schema(description = "")
  public ItemURN getItemURN() {
    return itemURN;
  }

  public void setItemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
  }

  public UpdateItemReq item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * Get item
   * @return item
  **/
  @Schema(description = "")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }

  public UpdateItemReq plan(Plan plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Get plan
   * @return plan
  **/
  @Schema(description = "")
  public Plan getPlan() {
    return plan;
  }

  public void setPlan(Plan plan) {
    this.plan = plan;
  }

  public UpdateItemReq isNewBabyPlan(String isNewBabyPlan) {
    this.isNewBabyPlan = isNewBabyPlan;
    return this;
  }

   /**
   * Get isNewBabyPlan
   * @return isNewBabyPlan
  **/
  @Schema(description = "")
  public String getIsNewBabyPlan() {
    return isNewBabyPlan;
  }

  public void setIsNewBabyPlan(String isNewBabyPlan) {
    this.isNewBabyPlan = isNewBabyPlan;
  }

  public UpdateItemReq newBabyPlanList(NewBabyPlanList newBabyPlanList) {
    this.newBabyPlanList = newBabyPlanList;
    return this;
  }

   /**
   * Get newBabyPlanList
   * @return newBabyPlanList
  **/
  @Schema(description = "")
  public NewBabyPlanList getNewBabyPlanList() {
    return newBabyPlanList;
  }

  public void setNewBabyPlanList(NewBabyPlanList newBabyPlanList) {
    this.newBabyPlanList = newBabyPlanList;
  }

  public UpdateItemReq mailer(Mailer mailer) {
    this.mailer = mailer;
    return this;
  }

   /**
   * Get mailer
   * @return mailer
  **/
  @Schema(description = "")
  public Mailer getMailer() {
    return mailer;
  }

  public void setMailer(Mailer mailer) {
    this.mailer = mailer;
  }

  public UpdateItemReq updateMailerStatus(String updateMailerStatus) {
    this.updateMailerStatus = updateMailerStatus;
    return this;
  }

   /**
   * Get updateMailerStatus
   * @return updateMailerStatus
  **/
  @Schema(description = "")
  public String getUpdateMailerStatus() {
    return updateMailerStatus;
  }

  public void setUpdateMailerStatus(String updateMailerStatus) {
    this.updateMailerStatus = updateMailerStatus;
  }

  public UpdateItemReq customerToken(String customerToken) {
    this.customerToken = customerToken;
    return this;
  }

   /**
   * Get customerToken
   * @return customerToken
  **/
  @Schema(description = "")
  public String getCustomerToken() {
    return customerToken;
  }

  public void setCustomerToken(String customerToken) {
    this.customerToken = customerToken;
  }

  public UpdateItemReq ovrBabyBSD(String ovrBabyBSD) {
    this.ovrBabyBSD = ovrBabyBSD;
    return this;
  }

   /**
   * Get ovrBabyBSD
   * @return ovrBabyBSD
  **/
  @Schema(description = "")
  public String getOvrBabyBSD() {
    return ovrBabyBSD;
  }

  public void setOvrBabyBSD(String ovrBabyBSD) {
    this.ovrBabyBSD = ovrBabyBSD;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateItemReq updateItemReq = (UpdateItemReq) o;
    return Objects.equals(this.sourceEvent, updateItemReq.sourceEvent) &&
        Objects.equals(this.itemID, updateItemReq.itemID) &&
        Objects.equals(this.itemURN, updateItemReq.itemURN) &&
        Objects.equals(this.item, updateItemReq.item) &&
        Objects.equals(this.plan, updateItemReq.plan) &&
        Objects.equals(this.isNewBabyPlan, updateItemReq.isNewBabyPlan) &&
        Objects.equals(this.newBabyPlanList, updateItemReq.newBabyPlanList) &&
        Objects.equals(this.mailer, updateItemReq.mailer) &&
        Objects.equals(this.updateMailerStatus, updateItemReq.updateMailerStatus) &&
        Objects.equals(this.customerToken, updateItemReq.customerToken) &&
        Objects.equals(this.ovrBabyBSD, updateItemReq.ovrBabyBSD);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceEvent, itemID, itemURN, item, plan, isNewBabyPlan, newBabyPlanList, mailer, updateMailerStatus, customerToken, ovrBabyBSD);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateItemReq {\n");
    
    sb.append("    sourceEvent: ").append(toIndentedString(sourceEvent)).append("\n");
    sb.append("    itemID: ").append(toIndentedString(itemID)).append("\n");
    sb.append("    itemURN: ").append(toIndentedString(itemURN)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    isNewBabyPlan: ").append(toIndentedString(isNewBabyPlan)).append("\n");
    sb.append("    newBabyPlanList: ").append(toIndentedString(newBabyPlanList)).append("\n");
    sb.append("    mailer: ").append(toIndentedString(mailer)).append("\n");
    sb.append("    updateMailerStatus: ").append(toIndentedString(updateMailerStatus)).append("\n");
    sb.append("    customerToken: ").append(toIndentedString(customerToken)).append("\n");
    sb.append("    ovrBabyBSD: ").append(toIndentedString(ovrBabyBSD)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
