/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BabyPlanList;
import io.swagger.client.model.ErrorResponseList;
import io.swagger.client.model.ItemID;
import io.swagger.client.model.ItemURN;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UpdateItemResp
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-19T12:25:14.024746100Z[Etc/UTC]")
public class UpdateItemResp {
  @SerializedName("ItemID")
  private ItemID itemID = null;

  @SerializedName("ItemURN")
  private ItemURN itemURN = null;

  @SerializedName("BabyPlanList")
  private BabyPlanList babyPlanList = null;

  @SerializedName("ErrorResponseList")
  private ErrorResponseList errorResponseList = null;

  public UpdateItemResp itemID(ItemID itemID) {
    this.itemID = itemID;
    return this;
  }

   /**
   * Get itemID
   * @return itemID
  **/
  @Schema(description = "")
  public ItemID getItemID() {
    return itemID;
  }

  public void setItemID(ItemID itemID) {
    this.itemID = itemID;
  }

  public UpdateItemResp itemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
    return this;
  }

   /**
   * Get itemURN
   * @return itemURN
  **/
  @Schema(description = "")
  public ItemURN getItemURN() {
    return itemURN;
  }

  public void setItemURN(ItemURN itemURN) {
    this.itemURN = itemURN;
  }

  public UpdateItemResp babyPlanList(BabyPlanList babyPlanList) {
    this.babyPlanList = babyPlanList;
    return this;
  }

   /**
   * Get babyPlanList
   * @return babyPlanList
  **/
  @Schema(description = "")
  public BabyPlanList getBabyPlanList() {
    return babyPlanList;
  }

  public void setBabyPlanList(BabyPlanList babyPlanList) {
    this.babyPlanList = babyPlanList;
  }

  public UpdateItemResp errorResponseList(ErrorResponseList errorResponseList) {
    this.errorResponseList = errorResponseList;
    return this;
  }

   /**
   * Get errorResponseList
   * @return errorResponseList
  **/
  @Schema(description = "")
  public ErrorResponseList getErrorResponseList() {
    return errorResponseList;
  }

  public void setErrorResponseList(ErrorResponseList errorResponseList) {
    this.errorResponseList = errorResponseList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateItemResp updateItemResp = (UpdateItemResp) o;
    return Objects.equals(this.itemID, updateItemResp.itemID) &&
        Objects.equals(this.itemURN, updateItemResp.itemURN) &&
        Objects.equals(this.babyPlanList, updateItemResp.babyPlanList) &&
        Objects.equals(this.errorResponseList, updateItemResp.errorResponseList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemID, itemURN, babyPlanList, errorResponseList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateItemResp {\n");
    
    sb.append("    itemID: ").append(toIndentedString(itemID)).append("\n");
    sb.append("    itemURN: ").append(toIndentedString(itemURN)).append("\n");
    sb.append("    babyPlanList: ").append(toIndentedString(babyPlanList)).append("\n");
    sb.append("    errorResponseList: ").append(toIndentedString(errorResponseList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
