/*
 * Items API V1
 * Items API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateItemReq;
import io.swagger.client.model.CreateItemResp;
import io.swagger.client.model.Error;
import io.swagger.client.model.GetItemDetailsResp;
import io.swagger.client.model.UpdateItemReq;
import io.swagger.client.model.UpdateItemResp;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemsApi
 */
@Ignore
public class ItemsApiTest {

    private final ItemsApi api = new ItemsApi();

    /**
     * Get a Single Item details by passing it&#x27;s ID
     *
     * get Item details by Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsIdGetTest() throws ApiException {
        String id = null;
        String entityId = null;
        String clientURN = null;
        String applianceToken = null;
        String systemCode = null;
        String countryCode = null;
        String clientCode = null;
        String clientGroupCode = null;
        String channelCode = null;
        String clientUserId = null;
        String clientPassword = null;
        GetItemDetailsResp response = api.itemsIdGet(id, entityId, clientURN, applianceToken, systemCode, countryCode, clientCode, clientGroupCode, channelCode, clientUserId, clientPassword);

        // TODO: test validations
    }
    /**
     * 
     *
     * updates an item by Id
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsIdPutTest() throws ApiException {
        UpdateItemReq body = null;
        String entityId = null;
        String clientURN = null;
        String applianceToken = null;
        String systemCode = null;
        String countryCode = null;
        String clientCode = null;
        String clientGroupCode = null;
        String channelCode = null;
        String clientUserId = null;
        String clientPassword = null;
        String id = null;
        UpdateItemResp response = api.itemsIdPut(body, entityId, clientURN, applianceToken, systemCode, countryCode, clientCode, clientGroupCode, channelCode, clientUserId, clientPassword, id);

        // TODO: test validations
    }
    /**
     * 
     *
     * creates Item
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsPostTest() throws ApiException {
        CreateItemReq body = null;
        String entityId = null;
        String clientURN = null;
        String applianceToken = null;
        String systemCode = null;
        String countryCode = null;
        String clientCode = null;
        String clientGroupCode = null;
        String channelCode = null;
        String clientUserId = null;
        String clientPassword = null;
        CreateItemResp response = api.itemsPost(body, entityId, clientURN, applianceToken, systemCode, countryCode, clientCode, clientGroupCode, channelCode, clientUserId, clientPassword);

        // TODO: test validations
    }
}
